[package]
name = "croatoan_core"
version = "0.1.0"
edition = "2021"

[dependencies]
croatoan_render = { path = "../croatoan_render" }
winit = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
wgpu = { workspace = true }
