[package]
name = "croatoan_render"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { workspace = true }
winit = { workspace = true }
log = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
pollster = "0.3"
